name: fooddelivery
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Base
  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.6
  intl: ^0.19.0
  google_fonts: ^6.1.0

  # FIREBASE PACKAGES
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_analytics: ^10.6.2
  firebase_remote_config: ^4.3.2
  firebase_storage: ^11.6.0

  # CONNECTIVITY
  share: ^2.0.4
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0

  # STATE MANAGEMENT
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1

  # MAP
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # UI
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_vector_icons: ^2.0.0
  country_code_picker: ^3.0.0
  sliding_up_panel: 2.0.0+1
  modal_bottom_sheet: ^2.1.2
  flutter_launcher_icons: ^0.14.3
  carousel_slider: ^5.0.0
  flutter_styled_toast: ^2.2.1
  flutter_screenutil: ^5.9.1
  salomon_bottom_bar: ^3.3.2
  provider:
  # WEB TOOLS
  html: ^0.15.4

  # AUTHENTICATION
  google_sign_in: ^6.1.5

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.0.3

  # IMAGES
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

  #PAGINATON
  paginate_firestore: ^1.0.3+1

  # APP LOCATION
  flutter_localizations:
    sdk: flutter

    #launcher
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/favicon.png"
  min_sdk_android: 21
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0


dependency_overrides:
  #  intl: ^0.18.0
  #  flutter_cache_manager: ^3.3.0
  #  file: ^6.1.4
  platform: ^3.1.3
  #  http: ^0.13.0
  cloud_firestore: ^4.8.0
  paginate_firestore: ^1.0.3+1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/placeholder.jpg
    - assets/food/
    - assets/
    - assets/flag/
    - lang/

