// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyxEVPVYC-zVHZNd2tr5JccCiefvj9UM4',
    appId: '1:76611240102:web:b977fb0781cdf00b61f467',
    messagingSenderId: '76611240102',
    projectId: 'mighty-food-cb139',
    authDomain: 'mighty-food-cb139.firebaseapp.com',
    storageBucket: 'mighty-food-cb139.firebasestorage.app',
    measurementId: 'G-XDJV73NERM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1_EBvRI4wK-MRM5wtg8Ksf6VBFvQbPR0',
    appId: '1:76611240102:android:b1c46e94b7c5ec6b61f467',
    messagingSenderId: '76611240102',
    projectId: 'mighty-food-cb139',
    storageBucket: 'mighty-food-cb139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQD3zSieQodlJY3XogEhVE5e1gXDn35I',
    appId: '1:76611240102:ios:331d09f0a49c942661f467',
    messagingSenderId: '76611240102',
    projectId: 'mighty-food-cb139',
    storageBucket: 'mighty-food-cb139.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQD3zSieQodlJY3XogEhVE5e1gXDn35I',
    appId: '1:76611240102:ios:331d09f0a49c942661f467',
    messagingSenderId: '76611240102',
    projectId: 'mighty-food-cb139',
    storageBucket: 'mighty-food-cb139.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyxEVPVYC-zVHZNd2tr5JccCiefvj9UM4',
    appId: '1:76611240102:web:9e878f8d32a4473b61f467',
    messagingSenderId: '76611240102',
    projectId: 'mighty-food-cb139',
    authDomain: 'mighty-food-cb139.firebaseapp.com',
    storageBucket: 'mighty-food-cb139.firebasestorage.app',
    measurementId: 'G-1S79ZG0T2H',
  );
}
